
{{- range $app := .Values.argocdApplications -}}
{{ if not .disable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ $.Values.global.env }}
  namespace: argocd
spec:
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL:  {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
  {{- if hasKey . "appCategory" }}
    path: manifests/{{ $.Values.global.env }}/{{ .appCategory }}/{{ .name }}
  {{- else }}
    path: manifests/{{ $.Values.global.env }}/{{ .name }}
  {{- end }}
  {{- if not (empty .directory) }}
    directory:
  {{- .directory | toYaml | nindent 6}}
  {{- end }}
  destination:
    namespace: {{ default $.Values.global.spec.destination.namespace .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if not .disableAutomated }}
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    {{- end }}
#    syncOptions:
#      - CreateNamespace=true
---
{{- end }}
{{- end }}