global:
  env: dev
  helmDefault: false
  valuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://github.com/dajrivera/k8s-cluster.git
      targetRevision: HEAD

argocdApplications:
  argocd:
    disableAutomated: false
    disable: false
    name: argocd
    namespace: argocd
    appCategory: apps
  talos:
    disableAutomated: false
    disable: false
    name: talos
    namespace: omni-system
    directory:
      recurse: false
      exclude: "{k8s-cluster.yaml,bootstrap/*}"
      # include: "omni-cluster-sync-job.yaml"
    appCategory: cluster
  omni:
    disableAutomated: false
    disable: false
    name: omni
    namespace: omni-system
    appCategory: cluster
    ignoreDifferences:
      - group: ""
        kind: Namespace
        jsonPointers:
          - /metadata/annotations/argocd.argoproj.io~1tracking-id    
  hostNetwork:
    disableAutomated: false
    disable: false
    name: host-network
    namespace: kube-system
    appCategory: infra
  multus:
    disableAutomated: false
    disable: false
    name: multus
    namespace: kube-system
    appCategory: infra
  cilium:
    disableAutomated: false
    disable: false
    name: cilium
    namespace: kube-system
    appCategory: infra
  argocdApps:
    disableAutomated: false
    disable: false
    name: argocd-apps
    namespace: argocd
    appCategory: apps
  certManager:
    disableAutomated: false
    disable: false
    name: cert-manager
    namespace: cert-manager
    appCategory: apps