apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: rook-ceph-cluster
name: rook-ceph-cluster
repo: https://charts.rook.io/release
chartHome: ../../../../../charts
releaseName: rook-ceph-cluster
namespace: rook-ceph
includeCRDs: true
skipHooks: false
version: 1.18.4