apiVersion: v1
data:
  00-multus.conf: |-
    {
        "cniVersion": "0.3.1",
        "logLevel": "debug",
        "logToStderr": true,
        "name": "multus-cni-network",
        "clusterNetwork": "/host/etc/cni/net.d/05-cilium.conflist",
        "type": "multus-shim"
    }
kind: ConfigMap
metadata:
  labels:
    app: multus
    tier: node
  name: multus-cni-config
  namespace: kube-system
