apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: public-net
  namespace: rook-ceph
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "public-net",
      "type": "bridge",
      "bridge": "br-ext",
      "vlan": 3000,
      "ipam": {
        "type": "host-local",
        "ranges": [
          [ {
            "subnet": "10.10.0.0/16",
            "rangeStart": "10.10.0.2",
            "rangeEnd": "10.10.255.253",
            "gateway": "10.10.255.254"
          } ]
        ]
      }
    }
