apiVersion: v1
data:
  daemon-config.json: |-
    {
        "chrootDir": "/hostroot",
        "cniVersion": "0.3.1",
        "logLevel": "debug",
        "logToStderr": true,
        "cniConfigDir": "/host/etc/cni/net.d",
        "multusAutoconfigDir": "/host/etc/cni/net.d",
        "multusConfigFile": "auto",
        "ReadinessIndicatorFile": "/host/etc/cni/net.d/05-cilium.conflist",
        "socketDir": "/host/run/multus/"
    }
kind: ConfigMap
metadata:
  labels:
    app: multus
    tier: node
  name: multus-daemon-config
  namespace: kube-system
