apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: argocd-apps
name: argocd-apps
chartHome: charts
releaseName: argocd-apps
namespace: argocd
includeCRDs: true
skipHooks: false