apiVersion: customFunction
kind: ClusterConfigHashGenerator
metadata:
  name: talos-cluster-config-generator
  annotations:
    config.kubernetes.io/function: |
      exec: 
        path: ./plugins/generate-cluster-config.sh
spec:
  configPaths:
    # relative to git top level
    - /k8s-cluster.yaml
    - /bootstrap
  outputPath: ../../../../../manifests/dev/cluster/talos