kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  00-multus.conf: |
    {
        "cniVersion": "0.3.1",
        "logLevel": "debug",
        "logToStderr": true,
        "name": "multus-cni-network",
        "clusterNetwork": "/host/etc/cni/net.d/05-cilium.conflist",
        "type": "multus-shim"
    }