apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/monitoring/kube-prometheus-stack/
generators:
  - ../../../../../helm/overlays/dev/monitoring/kube-prometheus-stack/