apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/version: v0.4.1
    helm.sh/chart: ceph-csi-operator-0.4.1
  name: ceph-csi-rbd-nodeplugin-rb
  namespace: ceph-csi-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-rbd-nodeplugin-r
subjects:
- kind: ServiceAccount
  name: ceph-csi-rbd-nodeplugin-sa
  namespace: rook-ceph
