apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/version: v0.4.1
    helm.sh/chart: ceph-csi-operator-0.4.1
  name: ceph-csi-nfs-nodeplugin-sa
  namespace: ceph-csi-operator-system
