apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/version: v0.4.1
    helm.sh/chart: ceph-csi-operator-0.4.1
  name: ceph-csi-nfs-nodeplugin-crb
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-nfs-nodeplugin-cr
subjects:
- kind: ServiceAccount
  name: ceph-csi-nfs-nodeplugin-sa
  namespace: rook-ceph
