apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/version: v1.18.6
    helm.sh/chart: rook-ceph-v1.18.6
    operator: rook
    storage-backend: ceph
  name: rook-ceph-osd
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ceph.rook.io
  resources:
  - cephclusters
  - cephclusters/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
