apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ceph-csi
    app.kubernetes.io/version: v0.4.1
    helm.sh/chart: ceph-csi-operator-0.4.1
  name: ceph-csi-metrics-auth-role
  namespace: rook-ceph
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
