apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/version: v1.18.6
    helm.sh/chart: rook-ceph-v1.18.6
    operator: rook
    storage-backend: ceph
  name: rook-ceph-mgr
  namespace: rook-ceph
