apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.14.8
    helm.sh/chart: argo-cd-7.8.14
  name: argocd-tls-certs-cm
  namespace: argocd
