apiVersion: v1
data:
  applicationsetcontroller.enable.leader.election: "false"
  applicationsetcontroller.log.format: text
  applicationsetcontroller.log.level: info
  commitserver.log.format: text
  commitserver.log.level: info
  controller.log.format: text
  controller.log.level: info
  dexserver.log.format: text
  dexserver.log.level: info
  notificationscontroller.log.format: text
  notificationscontroller.log.level: info
  redis.server: argo-cd-argocd-redis:6379
  repo.server: argo-cd-argocd-repo-server:8081
  reposerver.log.format: text
  reposerver.log.level: info
  server.log.format: text
  server.log.level: info
  server.repo.server.strict.tls: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.1.9
    helm.sh/chart: argo-cd-9.0.5
  name: argocd-cmd-params-cm
  namespace: argocd
