apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.1.9
    helm.sh/chart: argo-cd-9.0.5
  name: argo-cd-argocd-applicationset-controller
  namespace: argocd
spec:
  ports:
  - name: http-webhook
    port: 7000
    targetPort: webhook
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-applicationset-controller
  type: ClusterIP
