apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.1.8
    helm.sh/chart: argo-cd-8.5.8
  name: argo-cd-argocd-redis
  namespace: argocd
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-redis
