apiVersion: v1
kind: Service
metadata:
  annotations:
    omni-kube-service-exposer.sidero.dev/icon: H4sICLLnVmgAA2FyZ29jZC5zdmcArVlbb2O5Df4rgosCm4ej6C6dYjLA7jxsHjpAgaL77pz41nXiIHaS2fn1/UjqXBw7yRQYBNaVIj9RJEWdfNo/r9S3u+39/mq2Phwe/nF5+fLyol+83j2uLp0x5hIUM/WyuT2sr2YYmKn1YrNaH2rnebN4+W337WpmlFHWFfrNPn+6XSz3nz89zA9rtbm9mt0unjfd7v7Xx9Wuu8UqDH3FgjWIn/G7Nt9nl58/XcoqKbvt5uFfZ9fbWeVMXIJTwa5DeI72Orjvd+DKrPrl7zFyYPS0X6j142J5NfvbK5A/ysX/FC5hsqm7EnVqIzamrffbxukYVSza+XIdgi4l05h1sZHBHxYS/w+od/P9n6ccEjis1HKzPSwer2ZPj9tfjrl0F++KoJXbZvcw7zaHv65m2kXLYlf4kcC3xOafLNb9kNTyc6VG81rs6lRmO1N0Bg3ZwjmZ8aI3FOIOocub22XnxaVgDqEU5Q1klbnTbQ5KSvimsk3UbSiNNsa/mqRpnqS50YlWZyHOP4DoX0Nc+LDwNwKxBB2cUylqn/yeLLtxKL1tdImu8VYbb7/krC0cwLY6RK+S094m5YzOx5190VF57dtWFd26pGzSNvoOIlIdMQrsrYlD46Pd3XywO3eyuzbF0O/Oaxuiao0uKf9Rsg65I60LytJYgHetShrNFrrP1OwabMPgGBobaPeN18UFIojQDgi2rDLmsE/aF1pkWDsgkE7HnHG2tPNx5UAlnaO9i12fKqAbor015u9juJceRXpUf0klPP5zvzng/tjd/HfRHX7bPd3fbu5XuBSgqOXiy267e/w6PzxuvqnN/dXs37unx27x++P8Yb2BqOf59mmxl+tD7PDtlq3gRepwX7x1GIG0GVWBAtqwh32FrMTgKHYq1vIcZQhKSpbRkE84ZbXLeR5wSCGpWsk8nwBNhz2RZlY5DcKAbUcTnuhqTbLI5FNHLbZHLPIN85+2v9/5VltscU98GKh6BTQWJaWogxanEWhRXMgc8ORYUfKOPGEgK2CULJItrtYMjmHKbWN4URJo0/ZgQlOt36RuuZiL1q1p2fFCpiDUASZcnZRu2FoDvME2XEobAokAmpHRSthMCDsjNE7xXOBRkya8DNTLYrB14S2UahRk0lnoi7SMy9JDx3Xq8gQ6Ts6yq+bWK9iTgzgqrXSAnShIgdQ3WUhd32OiLxgrplXOa9PC1FqdDHuzSjBQhDI0O5FE6GmJmkpUwuws+luzKEvTozcIPrCCgtAK8BRgIk4NIRGm4FF5xFeuaq/jIBQJPg94IU59Typon8k8R9dyxKLSuI4pMvDXWSZVR9LOq3+R28Ffnc5pcjWQddON5KMaOsh9sDWKhxLpyMtgmNl4cZZOnBvuXBq5ANjjx+baGmjTd0GnTN7INUfcXNtURmya7iPxINq/RdiedvaQD1xWpyItMHeMja4xGeIUjcM2byD34MgTJeQD+dha49Bz6SLr2iiuGVmctrd1zwMKjvdocxOAXAx0+uAszs2iG+HKoaSrAYGA0rVgFStw2l5b3MMxAkt0XnbDEQXKAftpe9vC7eAVGVbdfnjESGyh53rCAqMe8dgZj7gZz5hg1ROWiIoD5hs+SqQcm9cFZmTbrqkn3ExOuDk94WaqzqPOvuk1muq9enTGMlIDdIBHs563lJEA63Uu491vuJLjmzS3NboeiatATg6T1VDtiM0h1MNk12BbRSmnN7auM0EmGFGSg8jXlxzdpPnPmBBwVEYHh8h0CFc+tyTcInj6howzV0iNVD3ABiSBdV2nmbY5oqUoIlRs5cccehqmoChSZ1sJ+lPSwcRW76dp9mL2IU04SeUmpmqNY8OLOF0Kp7hQCk4Oga31WfmsC0U/qlztdQ3TcDjlcSEufU8qusyYlTqaVcdElcTUYTUV29MeZXP0e+spgpuZ3hvnVJAviMFbC9u3F5aL135uLP2J8jKcJhVFQSbhAlGZ7tVG/ITtKTcIGLHv7Lnnq5lKGwltZuM37F9i1AgVmdPfIX4LZ4luk/bZSLRcLs/DC+Tigk54CDhuEzYBj2dGM0yHdoDmFPlQxUbNARxHVHb2Mm2fD5OTzLV14EWWJ7Ewc5jApYaLxHq6zhupaq8jWJBteLgIZW1XClNJKBFyMqVGgtKxCEpbhS+TqYkQYG5wxWRKFiaIRqoJzx5QroBynCAasE8gDWhleTqDqUwglR7Re0eMrN9AXYMOo07w16CRpEgG0EhVexQiQUCIqR+Ysm9XEsM0lCb0U3X1QEHzjhDLJAhTUkdyoEa8zpNlLQ6YBipiZPGanYLKPSg/AdXDn3NlVa3klXRE0dWN8egE0gDojBanrhwRdpGV4cJLlr8aSDYWx08KcfigME7VDwqRPjYgZtOekQKbuSRyUo4MkGwY+2qu52CJxfnk8ejZAWvByygiESj06cMYAmNMHF51lIxx+QdS8JKYpigpRZyOhfKBGPyZSR5viOSUe80DuHwGEuy5o6SGjovtlVNlrE3M5pQ7S8U8XujwfYpNhom8knIkYi5nGNBiIvDtuD1LwKgctpf67Sk3bsu3dVvHgzTW4VWCCId4R8cybMDXTc4RvVvKXakccEw2eYpfNvme50ZKuNjHkRfPJ5qtBsPB1ryaoCmZ+P7VB7bYTFcoEMZImTuVPQpEHc6FyL9g542ksxzz6RNMwO0jHfkyNcd128KFatWbpqVAimzNz6GjFKyqVVWhh8VbimQJGApnsCX70V7oQR55KigpqwKDq5nuHBvxMLFa8cO+geIDtMqheO7BpCArkEpe/nxDcbbiHX8I63/8JBiz1o5VwG+RsVECf84YDuitxODm7cQgcWJA/zX4/D8MKlc/XRgAAA==
    omni-kube-service-exposer.sidero.dev/label: Argo Dashboard
    omni-kube-service-exposer.sidero.dev/port: "50081"
    omni-kube-service-exposer.sidero.dev/prefix: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.1.9
    helm.sh/chart: argo-cd-9.0.5
  name: argo-cd-argocd-server
  namespace: argocd
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: ClusterIP
