apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.14.8
    helm.sh/chart: argo-cd-7.8.14
  name: argo-cd-argocd-repo-server
  namespace: argocd
spec:
  ports:
  - name: tcp-repo-server
    port: 8081
    protocol: TCP
    targetPort: repo-server
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-repo-server
