apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.14.8
    helm.sh/chart: argo-cd-7.8.14
  name: argo-cd-argocd-redis
  namespace: argocd
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-redis
