apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-dev
  namespace: argocd
spec:
  destination:
    namespace: talos-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: '{k8s-cluster.yaml,bootstrap/*}'
      recurse: false
    path: manifests/dev/cluster/talos
    repoURL: https://github.com/dajrivera/k8s-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
