apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/dev/cluster/gateway-api-crds
    repoURL: https://github.com/dajrivera/k8s-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
