apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cluster/rook-ceph-cluster/
generators:
  - ../../../../../helm/overlays/dev/cluster/rook-ceph-cluster/