kind: Cluster
name: k8s-homelab
kubernetes:
  version: v1.32.4
talos:
  version: v1.9.6
features:
  diskEncryption: true
  enableWorkloadProxy: true
  useEmbeddedDiscoveryService: true
patches:
  - name: clusterconfig
    inline:
      cluster:
        allowSchedulingOnControlPlanes: true
        apiServer:
          admissionControl:
            - name: PodSecurity
              configuration:
                exemptions:
                  namespaces:
                    - rook-ceph
          extraArgs:
            feature-gates: UserNamespacesSupport=true,UserNamespacesPodSecurityStandards=true
        network:
          cni:
            name: none
        proxy:
          disabled: true
      machine:
        kubelet:
          extraArgs:
            max-pods: "250"
          extraConfig:
            featureGates:
              UserNamespacesPodSecurityStandards: true
              UserNamespacesSupport: true
        features:
          hostDNS:
            enabled: true
            forwardKubeDNSToHost: false              
        sysctls:
          user.max_user_namespaces: "11255"
  - name: extramanifests
    file: manifests/dev/cluster/bootstrap/k8s-cluster-extramanifests.yaml
  - name: extramanifests-multus
    file: manifests/dev/cluster/bootstrap/k8s-cluster-extramanifests-multus.yaml
  - name: extramanifests-cilium
    file: manifests/dev/cluster/bootstrap/k8s-cluster-extramanifests-cilium.yaml
---
kind: ControlPlane
machineClass:
  name: homelab
  size: 1
patches:
  - name: machinepatch
    inline:
      machine:
        install:
          extraKernelArgs:
            - ipv6.disable=1
---
kind: Workers