apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  annotations:
    dashboard:
      omni-kube-service-exposer.sidero.dev/label: Ceph Dashboard
      omni-kube-service-exposer.sidero.dev/port: "50082"
      omni-kube-service-exposer.sidero.dev/prefix: cephdash
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v19.2.2
  cleanupPolicy:
    allowUninstallWithVolumes: false
    confirmation: ""
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    disable: false
  dashboard:
    enabled: true
    port: 8080
    ssl: false
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    allowMultiplePerNode: true
    count: 2
    modules:
    - enabled: true
      name: rook
  mon:
    allowMultiplePerNode: false
    count: 1
  monitoring:
    enabled: true
  network:
    provider: multus
    selectors:
      cluster: cluster-net
      public: public-net
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    cleanup:
      limits:
        memory: 1Gi
      requests:
        memory: 100Mi
    crashcollector:
      limits:
        memory: 60Mi
      requests:
        memory: 60Mi
    exporter:
      limits:
        memory: 128Mi
      requests:
        memory: 50Mi
    logcollector:
      limits:
        memory: 1Gi
      requests:
        memory: 100Mi
    mgr:
      limits:
        memory: 1Gi
      requests:
        memory: 512Mi
    mgr-sidecar:
      limits:
        memory: 100Mi
      requests:
        memory: 40Mi
    mon:
      limits:
        memory: 2Gi
      requests:
        memory: 1Gi
    osd:
      limits:
        memory: 4Gi
      requests:
        memory: 4Gi
    prepareosd:
      requests:
        memory: 50Mi
  skipUpgradeChecks: false
  storage:
    useAllDevices: true
    useAllNodes: true
  upgradeOSDRequiresHealthyPGs: false
  waitTimeoutForHealthyOSDInMinutes: 10
