apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: ceph-filesystem
  namespace: rook-ceph
spec:
  dataPools:
  - deviceClass: hdd
    failureDomain: host
    name: data0
    replicated:
      size: 1
  metadataPool:
    deviceClass: ssd
    failureDomain: host
    replicated:
      size: 1
  metadataServer:
    activeCount: 1
    activeStandby: true
    priorityClassName: system-cluster-critical
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: null
        memory: 4Gi
