apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-bucket
parameters:
  objectStoreName: ceph-objectstore
  objectStoreNamespace: rook-ceph
  region: us-west-1
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
volumeBindingMode: Immediate
